src/mime_types.rs

Also, the URL at the top of `mime_types.rs` 404s.

Change .js to application/javascript per RFC4329

---

src/lib.rs

Alternative way to use `Path` and `str` both (aslo `String`, `OsString`). Looks more generic than: https://github.com/cybergeek94/mime_guess/pull/5

Generic way to guess mime

---

src/mime_types.rs

There is a proposal to use "text/markdown" but it is still a draft
(https://datatracker.ietf.org/doc/draft-ietf-appsawg-text-markdown/)
in RFC editor queue so it seems wise to use "text/x-markdown" as long
as it is not official (see http://stackoverflow.com/a/25812177 for a
discussion on Markdown's mime type on Stack overflow).

Add Markdown (md) support

---

Cargo.toml
src/gen_mime_types.rs
src/lib.rs

This brings the benchmarks down from 60ns/350ns to 50ns/50ns for lowercase/uppercase on my machine.

Use Unicase to remove allocation when uppercase

---

src/lib.rs

User of this crate forced to add `mime` crate dependency even if it needs to interact with this crate only (because it return unwrapped `Mime` results).
This PR makes possible to reuse `mime` crate to prevent possible conflicts:
``` rust
error[E0308]: mismatched types
--> src\provider.rs:81:12
|
81 |                                    mime: guess_mime_type(path),
|                                          ^^^^^^^^^^^^^^^^^^^^^ expected struct `mime::Mime`, found a different struct `mime::Mime`
|
= note: expected type `mime::Mime` (struct `mime::Mime`)
= note:    found type `mime::Mime` (struct `mime::Mime`)
note: Perhaps two different versions of crate `mime` are being used?
```

Republish mime crate

---

Cargo.toml
build.rs
src/lib.rs

Previously, the build script would write generated code into the `src`
directory, which is not officially supported: when one depends on
mime_guess, the src dir is somewhere in `.cargo/registry`, and is
supposed to be immutable.
The correct way is to gen stuff into `OUT_DIR`, and this is exactly what
this commit is doing.
Additionally, it moves the build file to the now-default `build.rs`.
closes #31

Make build-script more Cargo-friendly

---

src/mime_types.rs

Python files (`*.py`) are plain text files.

Add `.py` as `text/plain`

---

src/mime_types.rs

`.hh` is sometimes used as an extension for C++ header files. Just like `.cc` or `.cpp`, it is `text/plain`.

Add `.hh` as `text/plain`

---

src/lib.rs

...that's similar to `get_mime_type_str` (returns `Option<&'static str>`) and change  `guess_mime_type_opt` to use it.

Add guess_mime_type_str

---

.travis.yml
README.md
src/lib.rs

These aren't actually stable yet, Rustdoc just doesn't bother to resolve the paths on non-nightly compilers: https://github.com/rust-lang/rust/issues/63305

fix intra-doc links

---

src/mime_types.rs

Per RFC https://tools.ietf.org/html/rfc7763
The official file types for markdown are .md, and .markdown
So .md should be text/markdown

Return correct mime type for md

---

Cargo.toml

We don't directly use phf in the build script, but we do need phf_shared to be
compiled with the unicase feature to work. The only way to do that is to
build-depend on phf with the unicase feature, so that phf_shared with unicase
is enabled.
This fixes a dependency declaration problem which was found by the new `-Z features` dependency resolver in cargo.
This and a publish will fix #56.

Add build dependency on phf with the unicase feature

---

src/mime_types.rs

The new media type is submitted to IANA but has not been formally
published by IANA yet. Both Firefox and Chromium are already using
the mime type for AVIF images.
Citation: https://aomediacodec.github.io/av1-avif/#mime-registration

Add AVIF media type registrations

---

src/lib.rs

Hello,
`get_mime_extensions_str` should not panic if the mime type does not contains `'/'` and return `None` instead.
Thank you very much in advance for your merge.
Cheers !

fix panic in get_mime_extensions_str

---

src/lib.rs

I wasn't sure if this was a typo or not. Should this be `octet-stream` instead of `content-stream`?
Thank you for the useful crate, by the way!

Replace `content-stream` with `octet-stream`

---

src/mime_types.rs

Cucumber is a Ruby software used for behavior-driven development (BDD).
The tests are written in the "Gherkin" language in text files with the '.feature' extension[^1].
A pure Rust implementation of [cucumber is available](https://github.com/bbqsrc/cucumber-rust).
The language description has been archived[^2].
The package `xdg-shared-mime-info` accepted[^3] the extension in its
database[^4] as 'text/x-gherkin'.
[^1] https://en.wikipedia.org/wiki/Cucumber_(software)#Gherkin_language
[^2] https://web.archive.org/web/20151025214933/https://cucumber.io/docs/reference
[^3] https://bugs.freedesktop.org/show_bug.cgi?id=95455
[^4] https://github.com/freedesktop/xdg-shared-mime-info/blob/dedbf256bf7e7a4ee106b645dc2bc0fc3b21ea8c/data/freedesktop.org.xml.in#L6009-L6013

Add new mimetype for '.feature' files used in cucumber (Gherkin)

---

src/mime_types.rs

It would seem that `image/pjpeg` is a weird thing invented by IE. I have been unable to find any references to it outside of that context (for example, in any RFC). Additionally, JFIF (jpeg file interchange format) does not imply progressive encoding, so I don't think this is correct anyway.

update entry for `jfif`

---

build.rs
src/impl_bin_search.rs
src/impl_phf.rs

Problem:
- When `include!(..)`ing the `mime_types_generated` file, it was assumed that the separator was `/`. However, this will occasionally break on windows causing a compile error.
Solution
- From the build script, embed the file path into a compile-time `env!` which uses the correct path separator.
Fixes #78

Use platform specific path separators

---

src/mime_types.rs

Instead of using the default application/octet-stream mime type for ics format use the appropriate text/calendar mime type according to RFC 2445 (https://www.ietf.org/rfc/rfc2445.txt).

refactor: use correct MIME type for ics

---

src/mime_types.rs

Add support for application `application/x-gzip`, equivalent of `application/gzip` since some servers still use this content-type header, example below
reference:
https://stackoverflow.com/questions/21870351/difference-between-x-gzip-and-gzip-for-content-encoding https://mimetype.io/application/x-gzip

Add support for application `application/x-gzip`

---

src/mime_types.rs

The `application/vnd.apache.parquet` mime type was recently registered with IANA: https://www.iana.org/assignments/media-types/application/vnd.apache.parquet
This also includes the deprecated `application/x-parquet` mime type in the list as it was mentioned on the media type assignment page above.

Add new mime type entry for `.parquet`

---

src/mime_types.rs

If you seach for "woff" within  https://www.iana.org/assignments/media-types/media-types.xhtml you'll find that `application/font-woff` has been deprecated and replaced with `font/woff`.

Update mime type of `.woff` files

---

src/mime_types.rs

Defaults to `image/qoi` as specified in xdg [here](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/master/data/freedesktop.org.xml.in) and in the relevant GitHub issue for QOI [here](https://github.com/phoboslab/qoi/issues/167), but also lists `image/x-qoi` as apparently some programs used to use that (see discussion in the linked issue).

feat: add support for QOI files
